Adding step for importing library

diff --git a/build-wheelhouse/action.yml b/build-wheelhouse/action.yml
--- a/build-wheelhouse/action.yml
+++ b/build-wheelhouse/action.yml
@@ -92,6 +92,18 @@ runs:
       run: |
         python -m pip install ${{ env.install_target }}
 
+    - name: "Verify library is properly installed"
+      shell: bash
+      run: |
+        library_name=${{ inputs.library-name }}
+
+        if python -c "import $library_name"; then
+            echo "Python module '$library_name' successfully imported."
+        else
+            echo "Failed to import Python module '$library_name': Something went wrong."
+            exit 1
+        fi
+
     - name: "Verify if importlib-metadata needs to be installed"
       shell: bash
       run: |
@@ -112,7 +124,8 @@ runs:
       run: |
         python -m pip install importlib-metadata
 
-    - name: "Verify library is properly installed and get its version number"
+
+    - name: "Get library version number"
       shell: bash
       run: |
         library_name=${{ inputs.library-name }}
