use toml to find towncrier directory, default to release branch, and assign someone to PR

diff --git a/doc-deploy-changelog/action.yml b/doc-deploy-changelog/action.yml
--- a/doc-deploy-changelog/action.yml
+++ b/doc-deploy-changelog/action.yml
@@ -59,6 +59,16 @@ inputs:
     default: true
     type: boolean
 
+  update-release-branch:
+    description: >
+      Whether or not to update the CHANGELOG in the release branch.
+      If ``true``, the branch used to update the CHANGELOG is "release/major.minor".
+      If ``false``, the branch used to update the CHANGELOG is
+      "maint/changelog-update-v${{ env.TAG_VERSION }}" and will be deleted after use.
+    required: false
+    default: true
+    type: boolean
+
 runs:
   using: "composite"
   steps:
@@ -79,24 +89,55 @@ runs:
     - name: Save tag version
       shell: bash
       run: |
-        # /refs/tags/v0.10.8 -> 0.10.8
+        # /refs/tags/v0.1.0 -> 0.1.0
         echo "TAG_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV
 
-    - name: "Install towncrier"
+    - name: "Install towncrier and toml"
       shell: bash
       run: |
-        python -m pip install --upgrade pip towncrier==23.11.0
+        python -m pip install --upgrade pip towncrier==23.11.0 toml==0.10.2
+
+    - name: "Get towncrier directory"
+      shell: python
+      run: |
+        import toml
+
+        # Load pyproject.toml
+        with open('pyproject.toml', 'r') as f:
+            config = toml.load(f)
+            directory=config["tool"]["towncrier"]["directory"]
+
+        # Get the GITHUB_ENV variable
+        github_env = os.getenv('GITHUB_ENV')
+
+        # Append the TOWNCRIER_DIR with its value to GITHUB_ENV
+        with open(github_env, "a") as f:
+            f.write(f"TOWNCRIER_DIR={directory}")
+
+    - name: "Set CHANGELOG update branch"
+      shell: bash
+      run: |
+        if [[ ${{ inputs.update-release-branch }} == "true" ]]; then
+          # Assume release branch is "release/major.minor"
+          # v0.1.0 (tag) -> release/0.1
+          tag_version=${{ env.TAG_VERSION }}
+          release_branch="release/${tag_version%.*}"
+          echo "UPDATE_BRANCH=$release_branch" >> $GITHUB_ENV
+        else
+          # maint/changelog-update-v0.1.0
+          echo "UPDATE_BRANCH=maint/changelog-update-v${{ env.TAG_VERSION }}" >> $GITHUB_ENV
+        fi
 
     - name: "Create new section in CHANGELOG and reupload tag"
       shell: bash
       run: |
-        # Get number of .md files in doc/changelog.d
+        # Get number of .md files in ${{ env.TOWNCRIER_DIR }}
         # Figure out how to use towncrier's directory from pyproject.toml
-        count=$(find doc/changelog.d -type f -name "*.md" | wc -l)
+        count=$(find ${{ env.TOWNCRIER_DIR }} -type f -name "*.md" | wc -l)
 
         if [ $count -gt 0 ]; then
           # Checkout branch from tag
-          git checkout -b maint/changelog-update-v${{ env.TAG_VERSION }}
+          git checkout -b ${{ env.UPDATE_BRANCH }}
 
           # Update the changelog with the package version from pyproject.toml
           # The [tool.towncrier] section in pyproject.toml requires the following line
@@ -118,7 +159,7 @@ runs:
           git config user.name 'pyansys-ci-bot'
           git config user.email 'pyansys.github.bot@ansys.com'
 
-          # Add CHANGELOG.md file and deleted doc/changelog.d/*.md files
+          # Add CHANGELOG.md file and deleted ${{ env.TOWNCRIER_DIR }}/*.md files
           git add .
 
           # Commit changes and save commit SHA
@@ -126,7 +167,7 @@ runs:
           echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
           # Push CHANGELOG.md changes
-          git push -u origin maint/changelog-update-v${{ env.TAG_VERSION }}
+          git push -u origin ${{ env.UPDATE_BRANCH }}
 
           echo "UPDATED_CHANGELOG=True" >> $GITHUB_ENV
         else
@@ -153,7 +194,7 @@ runs:
         # Push CHANGELOG.md changes to maint/v$version-changelog
         git push -u origin maint/v${{ env.TAG_VERSION }}-changelog
 
-        gh pr create --title "Update CHANGELOG for v${{ env.TAG_VERSION }}" --body "Update CHANGELOG for v${{ env.TAG_VERSION }} and remove .md files in doc/changelog.d"
+        gh pr create --title "Update CHANGELOG for v${{ env.TAG_VERSION }}" --body "Update CHANGELOG for v${{ env.TAG_VERSION }} and remove .md files in ${{ env.TOWNCRIER_DIR }}" --assignee ${{ github.actor }}
 
     - name: "Delete & Re-create tag"
       env:
@@ -162,7 +203,7 @@ runs:
       shell: bash
       run: |
           # Checkout branch created from tag with CHANGELOG update & pull
-          git checkout maint/changelog-update-v${{ env.TAG_VERSION }}
+          git checkout ${{ env.UPDATE_BRANCH }}
           git pull
 
           # Delete the tag locally
@@ -177,5 +218,10 @@ runs:
           # Create the tag on remote
           git push origin v${{ env.TAG_VERSION }}
 
-          # Delete branch created from deleted tag with CHANGELOG update
-          git push origin --delete maint/changelog-update-v${{ env.TAG_VERSION }}
+          if [[ ${{ inputs.update-release-branch }} == "false" ]]; then
+            # Delete branch created from deleted tag with CHANGELOG update
+            git push origin --delete ${{ env.UPDATE_BRANCH }}
+          fi
+
+          # Exit on error if the CHANGELOG is updated to prevent the release action from running
+          exit 1
