fail workflow if update-release-branch and update-main-branch are true

diff --git a/doc-deploy-changelog/action.yml b/doc-deploy-changelog/action.yml
--- a/doc-deploy-changelog/action.yml
+++ b/doc-deploy-changelog/action.yml
@@ -126,6 +126,15 @@ runs:
         python-version: ${{ env.PYTHON_VERSION }}
         use-cache: ${{ env.PYTHON_CACHE }}
 
+    - name: Check inputs are not both true
+      shell: bash
+      run: |
+        if [ "${{ inputs.update-release-branch }}" == "true" ] && [ "${{ inputs.update-main-branch }}" == "true" ]; then
+          echo "update-release-branch and update-main-branch cannot both be true."
+          echo "To update the main branch, set update-release-branch to false and update-main-branch to true."
+          exit 1
+        fi
+
     - name: Save tag version
       shell: bash
       run: |
