FEAT: multi-version documentation layout (#163)
Co-authored-by: Roberto Pastor Muela <37798125+RobPasMue@users.noreply.github.com>

diff --git a/doc-deploy-dev/action.yml b/doc-deploy-dev/action.yml
--- a/doc-deploy-dev/action.yml
+++ b/doc-deploy-dev/action.yml
@@ -1,5 +1,5 @@
 name: "Documentation deploy development version."
-description: "Deploy development documentation to GitHub pages."
+description: "Deploy development documentation artifacts to desired repository branch."
 
 inputs:
   doc-artifact-name:
@@ -7,10 +7,20 @@ inputs:
     required: false
     default: 'documentation-html'
     type: string
-  decompress_artifact:
+  decompress-artifact:
     description: "If ``True``, the documentation artifact name is decompressed. If ``False``, content is assumed to be a collection of HTML files."
     required: false
     default: false
+    type: string
+  repository:
+    description: "Name of the repository in the form of ``username/repository`` used to deploy the documentation. If not specified, current repository is used."
+    required: false
+    default: 'current'
+    type: string
+  branch:
+    description: "Desired deployment branch name. If not specified, ``gh-pages`` is used."
+    required: false
+    default: 'gh-pages'
     type: string
   cname:
     description: 'The canonical name of the documentation website.'
@@ -20,123 +30,145 @@ inputs:
     description: "Required token for documentation deployment."
     required: true
     type: string
-  workflow:
-    description: 'Workflow name from where the artifacts are downloaded. By default, the current running workflow.'
+  commit-message:
+    description: "Commit message used when deploying the documentation"
     required: false
-    default: ''
+    default: 'DOC: update development documentation'
     type: string
-  workflow-conclusion:
-    description: 'Workflow conclusion (options: "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required") or status (options: "completed", "in_progress", "queued") to search for. Use the empty string ("") to ignore status or conclusion in the search.'
-    required: false
-    default: ''
-    type: string
-  checkout:
-    description: 'If ``True``, the project is checked out in the ``gh-pages`` branch. If ``False``, users are the ones in charge of performing the checkout step.'
-    required: false
-    default: true
-    type: string
+
+
 
 runs:
   using: "composite"
   steps:
 
-    - name: "Install system dependencies"
+    # Checkout the repository branch for deploying the documentation. If this
+    # step fails, then it means that the provided token is not valid.
+
+    - name: "Get the name of the repository"
       shell: bash
       run: |
-        sudo apt-get install cargo curl
-        cargo install ouch && ouch --version
+        if [[ "${{ inputs.repository }}" == "current" ]]; then
+          echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
+        else
+          echo "REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV
+        fi
 
-    - name: "Checkout project in the GitHub Pages branch"
+    - name: "Checkout ${{ env.REPOSITORY }} repository"
       uses: actions/checkout@v3
-      if: inputs.checkout == 'true'
       with:
-        ref: 'gh-pages'
+        repository: ${{ env.REPOSITORY }}
+        ref: ${{ inputs.branch }}
+        token: ${{ inputs.token }}
 
-    - name: "Create a fresh development folder"
+    # Download the documentation artifact from the current workflow. If the
+    # artifact contains a compressed file, decompress it. Display the structure
+    # of the 'version/dev' directory at the end of the process to verify the
+    # layout of the folder is the right one.
+
+    - name: "Clean destination folder"
       shell: bash
-      run: |
-        rm -rf dev/ && mkdir dev/
+      run:
+        rm -rf version/dev && mkdir -p version/dev
 
-    - name: "Download the HTML documentation artifact from desired workflow"
-      uses: dawidd6/action-download-artifact@v2
-      if: inputs.workflow != ''
-      with:
-        github_token: ${{ inputs.token }}
-        name: ${{ inputs.doc-artifact-name }}
-        path: dev
-        workflow: ${{ inputs.workflow }}
-        workflow_conclusion: ${{ inputs.workflow-conclusion }}
-
-    - name: "Download the HTML documentation artifact from current workflow"
+    - name: "Download the development documentation artifact"
       uses: actions/download-artifact@v3
-      if: inputs.workflow == ''
       with:
         name: ${{ inputs.doc-artifact-name }}
-        path: dev
+        path: version/dev
 
-    - name: "Decompress artifact content if required"
+    - name: "Decompress artifact content"
       shell: bash
-      if: inputs.decompress_artifact == 'true'
-      working-directory: dev
+      if: inputs.decompress-artifact == 'true'
       run: |
-        compressed_artifact=$(ls .)
-        ouch decompress $compressed_artifact
-        rm $compressed_artifact
+        sudo apt-get install cargo && cargo install ouch && ouch --version
+        cd version/dev && compressed_artifact=$(ls .)
+        ouch decompress $compressed_artifact && rm $compressed_artifact
 
-    - name: "Display structure of downloaded files"
-      shell: bash
-      run: |
-        ls -R
-
-    - name: "Include CNAME and nojekyll files expected by GitHub pages"
+    - name: "Display structure of version/dev"
       shell: bash
       run: |
-        touch CNAME .nojekyll
-        echo ${{ inputs.cname }} > CNAME
+        ls -R version/dev
+
+    # Create the 'versions.json' file if it does not exist. Note that this step
+    # is not required in the 'doc-deploy-stable' action. The reason is that
+    # stable releases are born after a development version exists. This forces
+    # users to use this action before using the stable deploy one.
+
+    - name: "Create the 'versions.json' file if not present"
+      shell: bash
+      run: |
+        if ! [[ -f "versions.json" ]];
+        then
+            sudo apt-get install moreutils jq
+            echo '[]' > versions.json
+            url_dev="https://${{ inputs.cname }}/version/dev/"
+            jq --arg url $url_dev '. += [{"name": "dev", "version": "dev", "url": $url}]' versions.json | sponge versions.json
+        fi
+        cat versions.json
+
+    # Generate an 'index.html' for redirection to the latest stable version of
+    # the documentation. If no stable version has been release, a redirection
+    # to the development documentation is generated.
 
     - name: "Generate the redirection URL"
       shell: bash
       run: |
-        # Verify if there is any stable release in release/versions.json
-        if grep -q -E "\"version\": \"[0-9]+.[0-9]+ \(stable\)\"" release/versions.json;
+        if $(grep -q "(stable)" versions.json)
         then 
-          # Generate the URL pointing to the latest stable version
-          echo "Found stable release. Generating stable redirection URL..."
-          line=$(grep -n -E "\"version\": \"[0-9]+.[0-9]+ \(stable\)\"" release/versions.json)
-          version=$(echo $line | grep -o -h -E "[0-9]+.[0-9]+")
-          echo "URL=https://${{ inputs.cname }}/release/$version" >> $GITHUB_ENV
+          echo "Redirecting to the latest stable version..."
+          echo "REDIRECTION_URL=https://${{ inputs.cname }}/version/stable/" >> $GITHUB_ENV
         else 
-          # Generate the URL pointing to the development version if no stable releases
-          echo "Stable release not found. Generating development redirection URL..."
-          echo "URL=https://${{ inputs.cname }}/dev" >> $GITHUB_ENV
+          echo "Redirecting to the latest development version..."
+          echo "REDIRECTION_URL=https://${{ inputs.cname }}/version/dev/" >> $GITHUB_ENV
         fi
 
-    - name: "Update the redirection link"
+    - name: "Create the 'index.html' redirection file"
       shell: bash
       run: |
-        curl https://raw.githubusercontent.com/pyansys/actions/main/scripts/redirect.html -o index.html
-        # HACK: if the GitHub actions variable is dereferenced inside the `sed` command a syntax error is raised.
-        # The URL Github actions environmental variable is loaded inside a shell one to avoid this conflict.
-        url=${{ env.URL }}
-        echo "Value for url: $url"
-        sed -i "s|var-url|$url|g" index.html
-        cat index.html
+        echo "<!DOCTYPE html>" > index.html
+        echo "<meta charset=\"utf-8\">" >> index.html
+        echo "<title>Redirecting to ${{ env.REDIRECTION_URL }}</title>" >> index.html
+        echo "<meta http-equiv=\"refresh\" content=\"0; URL=${{ env.REDIRECTION_URL }}\">" >> index.html
+        echo "<link rel=\"canonical\" href=\"${{ env.REDIRECTION_URL }}\">" >> index.html
 
-    - name: "Clear unnecessary gh-pages files and directories"
+    - name: "Show the contents of the 'index.html' redirection file"
       shell: bash
       run: |
-        shopt -s extglob
-        rm -rf -v !("index.html"|"release"|"dev"|"CNAME"|".nojekyll")
-        ls -R
+          cat index.html
 
-    - name: "Commit new changes (if required)"
+    # Create the '.nojekyll' and 'CNAME' file with the desired values
+
+    - name: "Create '.nojekyll' and 'CNAME' files"
       shell: bash
       run: |
-        if [[ ! -z $(git status -s) ]];
-        then
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-          git add .
-          git commit -m "DOC: add development documentation"
-          git push
-        fi
+          touch .nojekyll CNAME
+          echo "${{ inputs.cname }}" > CNAME
+      
+    # For deploying the documentation, a GitHub token or a deployment token is
+    # required. The GitHub token is used when deploying to the current
+    # repository while the deployment token is used to deploy to an external
+    # repository.
+
+    - name: "Deploy to ${{ inputs.branch }} branch of ${{ github.repository }} repository"
+      if: inputs.repository == 'current'
+      uses: peaceiris/actions-gh-pages@v3
+      with:
+        publish_dir: .
+        publish_branch: ${{ inputs.branch }}
+        github_token: ${{ inputs.token }}
+        commit_message: ${{ inputs.commit-message }}
+        keep_files: true
+        force_orphan: true
+
+    - name: "Deploy to ${{ inputs.branch }} branch of ${{ inputs.repository }}"
+      if: inputs.repository != 'current'
+      uses: peaceiris/actions-gh-pages@v3
+      with:
+        publish_dir: .
+        publish_branch: ${{ inputs.branch }}
+        personal_token: ${{ inputs.token }}
+        external_repository: ${{ inputs.repository }}
+        commit_message: ${{ inputs.commit-message }}
+        keep_files: true
+        force_orphan: true
diff --git a/doc-deploy-stable/action.yml b/doc-deploy-stable/action.yml
--- a/doc-deploy-stable/action.yml
+++ b/doc-deploy-stable/action.yml
@@ -1,5 +1,5 @@
 name: "Documentation deploy stable version."
-description: "Deploy stable documentation to GitHub pages."
+description: "Deploy stable documentation artifacts to desired repository branch."
 
 inputs:
   doc-artifact-name:
@@ -7,158 +7,283 @@ inputs:
     required: false
     default: 'documentation-html'
     type: string
-  decompress_artifact:
+  decompress-artifact:
     description: "If ``True``, the documentation artifact name is decompressed. If ``False``, content is assumed to be a collection of HTML files."
     required: false
     default: false
+    type: string
+  repository:
+    description: "Name of the repository in the form of ``username/repository`` used to deploy the documentation. If not specified, current repository is used."
+    required: false
+    default: 'current'
+    type: string
+  branch:
+    description: "Desired deployment branch name. If not specified, ``gh-pages`` is used."
+    required: false
+    default: 'gh-pages'
     type: string
   cname:
     description: 'The canonical name of the documentation website.'
     required: true
     type: string
-  version-config:
-    description: 'Name of the JSON file specifying version configuration.'
-    default: 'versions.json'
-    required: false
-    type: string
   token:
     description: "Required token for documentation deployment."
     required: true
     type: string
-  python-version:
-    description: 'Desired Python version.'
-    default: '3.10'
+  commit-message:
+    description: "Commit message used when deploying the documentation"
     required: false
+    default: 'DOC: update development documentation'
     type: string
   render-last:
     description: 'Number of last versions to be rendered in multi-doc.'
     default: '3'
     required: false
     type: string
-  checkout:
-      description: 'Whether to checkout the repository or not.'
-      default: true
-      required: false
-      type: boolean
 
 runs:
   using: "composite"
   steps:
 
-    - name: "Checkout project in the GitHub Pages branch"
+    # Collect the version number from the tag or the branch name according to
+    # the reference type. Tags names are expected to follow 'v<MAJOR>.<MINOR>'
+    # or 'v<MAJOR>.<MINOR>.<PATCH>'. Braches must follow
+    # 'release/<MAJOR>.<MINOR>'.
+
+    - name: "Collect version number from the tag"
+      shell: bash
+      if: github.ref_type == 'tag'
+      run: |
+        tag=${{ github.ref_name }}
+        version=$( echo $tag | cut -d 'v' -f 2)
+
+        if [[ $version =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
+          echo "VERSION_RAW=$(echo $version)" >> $GITHUB_ENV
+        else
+          echo "[PYANSYS ACTIONS ERROR]"
+          echo "Tag names must follow 'v<MAJOR>.<MINOR>.<PATCH> name convention.'"
+          exit 1
+        fi
+
+    - name: "Collect version number from the release branch"
+      shell: bash
+      if: github.ref_type == 'branch'
+      run: |
+        tag=${{ github.ref_name }}
+        version=$( echo $tag | cut -d 'release/' -f 2)
+
+        if [[ $version =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
+          echo "VERSION_RAW=$(echo $version)" >> $GITHUB_ENV
+        else
+          echo "[PYANSYS ACTIONS ERROR]"
+          echo "Branch names must follow 'release/<MAJOR>.<MINOR>' name convention."
+          exit 1
+        fi
+
+    - name: "Assemble the version number using the collected major and minor numbers"
+      shell: bash
+      run: |
+          major=$(echo ${{ env.VERSION_RAW }} | cut -d . -f 1)
+          minor=$(echo ${{ env.VERSION_RAW }} | cut -d . -f 2)
+          echo "VERSION=$major.$minor" >> $GITHUB_ENV
+
+    # Checkout the repository branch for deploying the documentation. If this
+    # step fails, then it means that the provided token is not valid.
+
+    - name: "Get the name of the repository"
+      shell: bash
+      run: |
+        if [[ "${{ inputs.repository }}" == "current" ]]; then
+          echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
+        else
+          echo "REPOSITORY=${{ inputs.repository }}" >> $GITHUB_ENV
+        fi
+
+    - name: "Checkout ${{ env.REPOSITORY }} repository"
       uses: actions/checkout@v3
-      if: ${{ inputs.checkout == 'true' }}
       with:
-        ref: 'gh-pages'
+        repository: ${{ env.REPOSITORY }}
+        ref: ${{ inputs.branch }}
+        token: ${{ inputs.token }}
 
-    - name: "List gh-pages content"
+    # Download the stable documentation artifact in a folder that has the same
+    # name as the version number. Decompress artifact if required. Finally,
+    # display the structure of the directory to verify that it has the right
+    # layout.
+
+    - name: "Clean version content"
       shell: bash
       run: |
-        ls -R
+        if [ -d version/${{ env.VERSION }} ]; then
+          echo "VERSION_EXISTS=true" >> $GITHUB_ENV
+        else
+          echo "VERSION_EXISTS=false" >> $GITHUB_ENV
+        fi
+        rm -rf version/${{ env.VERSION }} && mkdir -p version/${{ env.VERSION }}
 
-    - name: "Check adequate version tagging"
-      shell: bash
-      run: |
-        # Remove the 'v' or the 'release/' at the beginning of the tag
-        ref_name="${{ github.ref_name }}"
-        version=${ref_name##*v}
-        version=${version##*release/}
-        # HACK: pydfp uses release-X.Y.Z
-        version=${version##*release-}
-        # Check that the version is of the accepted format
-        echo "ACCEPTED_FORMAT=$([[ "$version" =~ ^[0-9]+\.[0-9]+$|^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo "true" || echo "false")" >> $GITHUB_ENV
-        echo "PRELIMINARY_VERSION=$version" >> $GITHUB_ENV
-
-    - name: "Ignoring deployment... invalid version format!"
-      if: env.ACCEPTED_FORMAT == 'false'
-      shell: bash
-      run: |
-        echo "INVALID VERSION FORMAT - $PRELIMINARY_VERSION"
-        echo "Should be of type X.Y or X.Y.Z... Ignoring documentation deployment."
-
-    - name: "Prepare destination folder"
-      if: env.ACCEPTED_FORMAT == 'true'
-      shell: bash
-      run: |
-        # Filter out the major and minor version numbers
-        major=$(echo $PRELIMINARY_VERSION | cut -d. -f1)
-        minor=$(echo $PRELIMINARY_VERSION | cut -d. -f2)
-        folder=release/$major.$minor
-        echo "Folder was found to be $folder"
-        # Create a new folder for the version (remove existing one if required)
-        if [[ -d $folder ]]; then rm -rf $folder; fi 
-        mkdir -p $folder
-        # Output the version
-        echo "VERSION=$major.$minor" >> $GITHUB_ENV
-
-    - name: "Download the HTML documentation artifact in release/${{ github.ref_name }}"
-      if: env.ACCEPTED_FORMAT == 'true'
+    - name: "Download the stable documentation artifact"
       uses: actions/download-artifact@v3
       with:
         name: ${{ inputs.doc-artifact-name }}
-        path: release/${{ env.VERSION }}
+        path: version/${{ env.VERSION }}
 
-    - name: "Decompress artifact content if required"
+    - name: "Decompress artifact content"
       shell: bash
-      working-directory: release/${{ env.VERSION }}
-      if: inputs.decompress_artifact == 'true'
+      if: inputs.decompress-artifact == 'true'
       run: |
-        sudo apt-get install cargo
-        cargo install ouch && ouch --version
+        sudo apt-get install cargo && cargo install ouch && ouch --version
+        cd version/${{ env.VERSION }} && compressed_artifact=$(ls .)
+        ouch decompress $compressed_artifact && rm $compressed_artifact
 
-        compressed_artifact=$(ls .)
-        ouch decompress $compressed_artifact
-        rm $compressed_artifact
-  
-    - name: "Set up Python ${{ inputs.python-version }}"
-      if: env.ACCEPTED_FORMAT == 'true'
-      uses: pyansys/actions/_setup-python@main
+    - name: "Display structure of version/dev"
+      shell: bash
+      run: |
+        ls -R version/${{ env.VERSION }}
+
+    # Collect all stable releases (X.Y). Crop until matching the desired number
+    # to be displayed in the switcher. Generate the 'versions.json' file including
+    # development and latest stable links.
+
+    - name: "Install 'sponge' and 'jq' for manipulating JSON files"
+      shell: bash
+      run: |
+        sudo apt-get install moreutils jq
+
+    - name: "Create a clean 'versions.json' file"
+      shell: bash
+      run: |
+        rm -rf versions.json && touch versions.json && echo '[]' > versions.json
+
+    - name: "Add the development version to the 'versions.json' file"
+      shell: bash
+      run: |
+        url_dev="https://${{ inputs.cname }}/version/dev/"
+        jq --arg url $url_dev '. += [{"name": "dev", "version": "dev", "url": $url}]' versions.json | sponge versions.json
+        cat versions.json
+
+    - name: "Populate the 'versions.json' file with the desired amount of versions"
+      shell: bash
+      run: |
+        for version in $( ls version | \
+                          grep -E "^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$" | \
+                          sort -r --version-sort | \
+                          head -${{ inputs.render-last }}); do
+          url="https://${{ inputs.cname }}/version/$version/"
+          jq --arg version $version --arg url $url '. += [{"name": $version, "version": $version, "url": $url}]' < versions.json | sponge versions.json
+        done
+
+        cat versions.json
+
+    - name: "Convert the first stable version into the 'stable' one"
+      shell: bash
+      run: |
+        jq '.[1].name += " (stable)"' versions.json | sponge versions.json
+        url_stable="https://${{ inputs.cname }}/version/stable/"
+        jq --arg url $url_stable '.[1].url = $url' versions.json | sponge versions.json
+        cat versions.json
+
+    - name: "Find the latest stable version"
+      shell: bash
+      run: |
+        stable_version=$(jq '.[1].version' versions.json | grep -o '".*"' | sed 's/"//g')
+        echo "LATEST_STABLE_VERSION=$stable_version" >> $GITHUB_ENV
+
+    - name: "Update the content for the 'version/stable' folder"
+      shell: bash
+      run: |
+        rm -rf version/stable && cp -r version/${{ env.LATEST_STABLE_VERSION }} version/stable
+
+    # Generate the content for the announcement file. Place a copy of this file
+    # in each one of outdated stable versions. 
+
+    - name: "Generate the template content for the 'announcement.html' file"
+      shell: bash
+      run: |
+        cat > announcement.html <<'EOF'  
+          <p>
+            You are not viewing the most recent version of this documentation.
+            The latest stable release is <a href="STABLE_URL">LATEST_STABLE_VERSION</a>
+          </p>
+        EOF
+
+    - name: "Render the 'announcement.html' template with the desired stable version"
+      shell: bash
+      run: |
+        latest_stable_version=${{ env.LATEST_STABLE_VERSION}}
+        stable_url="https://${{ inputs.cname }}/version/stable/"
+        sed -i "s|LATEST_STABLE_VERSION|$latest_stable_version|g" announcement.html
+        sed -i "s|STABLE_URL|$stable_url|g" announcement.html
+
+    - name: "Place the 'announcement.html' file in every public folder of all the outdated versions"
+      shell: bash
+      run: |
+        for version_dir in $( ls version | \
+                          grep -E "^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$" | \
+                          grep -v "${{ env.LATEST_STABLE_VERSION }}" | \
+                          sort -r --version-sort ); do
+            find version/$version_dir -type d -not \( -path "*/_*" -type d -prune \) -exec cp announcement.html {} \;
+        done
+
+    - name: "Delete the 'announcement.html' file used as template"
+      shell: bash
+      run: |
+        rm -rf announcement.html
+
+    # Generate the redirection link. Since this is the stable documentation
+    # deployment action, there is always a 'version/stable' folder. Hence,
+    # redirection link always points to this folder.
+
+    - name: "Generate the redirection URL"
+      shell: bash
+      run: |
+        echo "REDIRECTION_URL=https://${{ inputs.cname }}/version/stable/" >> $GITHUB_ENV
+
+    - name: "Create the 'index.html' redirection file"
+      shell: bash
+      run: |
+        echo "<!DOCTYPE html>" > index.html
+        echo "<meta charset=\"utf-8\">" >> index.html
+        echo "<title>Redirecting to ${{ env.REDIRECTION_URL }}</title>" >> index.html
+        echo "<meta http-equiv=\"refresh\" content=\"0; URL=${{ env.REDIRECTION_URL }}\">" >> index.html
+        echo "<link rel=\"canonical\" href=\"${{ env.REDIRECTION_URL }}\">" >> index.html
+
+    - name: "Show the contents of the 'index.html' redirection file"
+      shell: bash
+      run: |
+          cat index.html
+
+    # Create the '.nojekyll' and 'CNAME' file with the desired values
+
+    - name: "Create '.nojekyll' and 'CNAME' files"
+      shell: bash
+      run: |
+          touch .nojekyll CNAME
+          echo "${{ inputs.cname }}" > CNAME
+
+    # For deploying the documentation, a GitHub token or a deployment token is
+    # required. The GitHub token is used when deploying to the current
+    # repository while the deployment token is used to deploy to an external
+    # repository.
+
+    - name: "Deploy to ${{ inputs.branch }} branch of ${{ github.repository }} repository"
+      if: inputs.repository == 'current'
+      uses: peaceiris/actions-gh-pages@v3
       with:
-        python-version: ${{ inputs.python-version }}
-        use-cache: false
+        publish_dir: .
+        publish_branch: ${{ inputs.branch }}
+        github_token: ${{ inputs.token }}
+        commit_message: ${{ inputs.commit-message }}
+        keep_files: true
+        force_orphan: true
 
-    - name: "Install system dependencies for updating version table"
-      if: env.ACCEPTED_FORMAT == 'true'
-      shell: bash
-      run: |
-        sudo apt-get install curl
-        python -m pip install -U pip
-
-    - name: "Get the version_mapper.py utility"
-      if: env.ACCEPTED_FORMAT == 'true'
-      shell: bash
-      run: |
-        curl https://raw.githubusercontent.com/pyansys/actions/main/scripts/version_mapper.py -o version_mapper.py
-        curl https://raw.githubusercontent.com/pyansys/actions/main/scripts/redirect.html -o index.html
-
-    - name: "Update the version JSON file"
-      if: env.ACCEPTED_FORMAT == 'true'
-      shell: bash
-      run: | 
-        python version_mapper.py \
-          --cname ${{ inputs.cname }} \
-          --json_filename ${{ inputs.version-config }} \
-          --new_version ${{ env.VERSION }} \
-          --render_last ${{ inputs.render-last }}
-        # Remove the script to avoid Git tracking it
-        rm -rf version_mapper.py
-
-    - name: "Clear unnecessary gh-pages files and directories"
-      shell: bash
-      run: |
-        shopt -s extglob
-        rm -rf -v !("index.html"|"release"|"dev"|"CNAME"|".nojekyll")
-        ls -R
-
-    - name: "Commit new changes (if required)"
-      if: env.ACCEPTED_FORMAT == 'true'
-      shell: bash
-      run: |
-          if [[ ! -z $(git status -s) ]];
-          then
-            git config user.name github-actions
-            git config user.email github-actions@github.com
-            git add .
-            git commit -m "DOC: add documentation for ${{ github.ref_name }}"
-            git push
-          fi
+    - name: "Deploy to ${{ inputs.branch }} branch of ${{ inputs.repository }}"
+      if: inputs.repository != 'current'
+      uses: peaceiris/actions-gh-pages@v3
+      with:
+        publish_dir: .
+        publish_branch: ${{ inputs.branch }}
+        personal_token: ${{ inputs.token }}
+        external_repository: ${{ inputs.repository }}
+        commit_message: ${{ inputs.commit-message }}
+        keep_files: true
+        force_orphan: true
