feat: check actions security action (#725)
Co-authored-by: pyansys-ci-bot <92810346+pyansys-ci-bot@users.noreply.github.com>
Co-authored-by: Jorge Martínez <28702884+jorgepiloto@users.noreply.github.com>
Co-authored-by: Sébastien Morais <146729917+SMoraisAnsys@users.noreply.github.com>

diff --git a/_doc-build-linux/action.yml b/_doc-build-linux/action.yml
--- a/_doc-build-linux/action.yml
+++ b/_doc-build-linux/action.yml
@@ -136,19 +136,23 @@ runs:
   steps:
 
     - name: "Collect system dependencies"
+      id: needed-dependencies
+      env:
+        DEPENDENCIES: ${{ inputs.dependencies }}
+        REQUIRES_XVFB: ${{ inputs.requires-xvfb }}
       shell: bash
       run: |
-        if [[ ${{ inputs.requires-xvfb }} == 'true' ]]; then
-          echo "NEEDED_DEPS=$(echo '${{ inputs.dependencies }} xvfb')" >> $GITHUB_ENV
+        if [[ "$REQUIRES_XVFB" == 'true' ]]; then
+          echo "NEEDED_DEPS=$(echo "$DEPENDENCIES xvfb")" >> $GITHUB_OUTPUT
         else
-          echo "NEEDED_DEPS=$(echo '${{ inputs.dependencies }}')" >> $GITHUB_ENV
+          echo "NEEDED_DEPS=$(echo "$DEPENDENCIES")" >> $GITHUB_OUTPUT
         fi
 
     - name: "Cache apt packages needed"
       uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 # v1.4.3
-      if: inputs.skip-dependencies-cache == 'false' && env.NEEDED_DEPS != ''
+      if: inputs.skip-dependencies-cache == 'false' && steps.needed-dependencies.outputs.NEEDED_DEPS != ''
       with:
-        packages: ${{ env.NEEDED_DEPS }}
+        packages: ${{ steps.needed-dependencies.outputs.NEEDED_DEPS }}
         version: 1.0
 
     - name: "Update apt-get"
@@ -158,8 +162,10 @@ runs:
 
     - name: "Install system dependencies"
       shell: bash
+      env:
+        NEEDED_DEPS: ${{ steps.needed-dependencies.outputs.NEEDED_DEPS }}
       run: |
-        sudo apt-get install -y ${{ env.NEEDED_DEPS }}
+        sudo apt-get install -y $NEEDED_DEPS
 
     - name: "Install LaTeX"
       shell: bash
@@ -194,22 +200,23 @@ runs:
           Determine context.
 
     - name: "Determine GitHub environment variables"
+      id: environment-variables
       shell: bash
       run: |
         if [[ -f "pyproject.toml" ]] && grep -q 'build-backend = "poetry\.core\.masonry\.api"' "pyproject.toml"; then
-          echo "BUILD_BACKEND=$(echo 'poetry')" >> $GITHUB_ENV
-          echo "SPHINX_BUILD_MAKE=$(echo 'poetry run -- make')" >> $GITHUB_ENV
+          echo "BUILD_BACKEND=$(echo 'poetry')" >> $GITHUB_OUTPUT
+          echo "SPHINX_BUILD_MAKE=$(echo 'poetry run -- make')" >> $GITHUB_OUTPUT
         else
-          echo "BUILD_BACKEND=$(echo 'pip')" >> $GITHUB_ENV
-          echo "SPHINX_BUILD_MAKE=$(echo 'make')" >> $GITHUB_ENV
+          echo "BUILD_BACKEND=$(echo 'pip')" >> $GITHUB_OUTPUT
+          echo "SPHINX_BUILD_MAKE=$(echo 'make')" >> $GITHUB_OUTPUT
         fi
 
     - uses: ansys/actions/_logging@main
       with:
         level: "INFO"
         message: >
-          Build backend: ${{ env.BUILD_BACKEND }}
-          Sphinx build make: ${{ env.SPHINX_BUILD_MAKE }}
+          Build backend: ${{ steps.environment-variables.outputs.BUILD_BACKEND }}
+          Sphinx build make: ${{ steps.environment-variables.outputs.SPHINX_BUILD_MAKE }}
 
     # ------------------------------------------------------------------------
 
@@ -224,17 +231,17 @@ runs:
     # dependencies with different version. This can lead to CICD failures. For
     # more information, see https://github.com/ansys/actions/pull/560
     - name: "Add pipx/bin directory to Github Path"
-      if: env.BUILD_BACKEND == 'poetry'
+      if: steps.environment-variables.outputs.BUILD_BACKEND == 'poetry'
       shell: bash
-      run: echo "${{ runner.temp }}/pipx/bin" >> $GITHUB_PATH
+      run: echo "${{ runner.temp }}/pipx/bin" >> $GITHUB_PATH  # zizmor: ignore[github-env]
 
     # NOTE: Poetry uses virtual environments when installing a project. As we
     # want to control that creation, we store POETRY_VIRTUALENVS_CREATE=false
     # in the GitHub environment.
     - name: "Set poetry environment variable(s)"
-      if: env.BUILD_BACKEND == 'poetry'
+      if: steps.environment-variables.outputs.BUILD_BACKEND == 'poetry'
       shell: bash
-      run: echo "POETRY_VIRTUALENVS_CREATE=false" >> $GITHUB_ENV
+      run: echo "POETRY_VIRTUALENVS_CREATE=false" >> $GITHUB_ENV # zizmor: ignore[github-env]
 
     # NOTE: Install pipx in a location that can be used in following CICD jobs
     # but ensure that poetry is installed in a temporary folder cleaned before
@@ -242,7 +249,7 @@ runs:
     # making it available in the following call and installed in a different
     # environment from the project.
     - name: "Install poetry and create a virtual environment"
-      if: env.BUILD_BACKEND == 'poetry'
+      if: steps.environment-variables.outputs.BUILD_BACKEND == 'poetry'
       shell: bash
       run: |
         python -m pip install pipx
@@ -253,7 +260,7 @@ runs:
         PIPX_HOME : ${{ runner.temp }}/pipx/home
 
     - name: "Create a virtual environment"
-      if: env.BUILD_BACKEND == 'pip'
+      if: steps.environment-variables.outputs.BUILD_BACKEND == 'pip'
       shell: bash
       run: |
         python -m venv .venv
@@ -267,23 +274,30 @@ runs:
         python -m pip install -U pip
 
     - name: "Check if requirements.txt file exists"
+      id: check-requirement-file-exists
       shell: bash
+      env:
+        REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
       run: |
-        echo "EXISTS_DOC_REQUIREMENTS=$(if [ -f ${{ inputs.requirements-file }} ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV
+        echo "EXISTS_DOC_REQUIREMENTS=$(if [ -f "${REQUIREMENTS_FILE}" ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT
 
     - name: "Install documentation dependencies from requirements file"
       shell: bash
-      if: env.EXISTS_DOC_REQUIREMENTS == 'true'
+      env:
+        REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
+      if: steps.check-requirement-file-exists.outputs.EXISTS_DOC_REQUIREMENTS == 'true'
       run: |
         source .venv/bin/activate
-        python -m pip install -r ${{ inputs.requirements-file }}
+        python -m pip install -r "${REQUIREMENTS_FILE}"
 
     - name: "Install Python library"
       shell: bash
       if: inputs.skip-install == 'false'
+      env:
+        BUILD_BACKEND: ${{ steps.environment-variables.outputs.BUILD_BACKEND }}
       run: |
         source .venv/bin/activate
-        if [[ ${{ env.BUILD_BACKEND }} == 'poetry' ]]; then
+        if [[ "${BUILD_BACKEND}" == 'poetry' ]]; then
           poetry install
         else
           python -m pip install .
@@ -291,10 +305,12 @@ runs:
 
     - name: "Install documentation dependencies from pyproject.toml"
       shell: bash
-      if: env.EXISTS_DOC_REQUIREMENTS == 'false'
+      if: steps.check-requirement-file-exists.outputs.EXISTS_DOC_REQUIREMENTS == 'false'
+      env:
+        BUILD_BACKEND: ${{ steps.environment-variables.outputs.BUILD_BACKEND }}
       run: |
         source .venv/bin/activate
-        if [[ ${{ env.BUILD_BACKEND }} == 'poetry' ]]; then
+        if [[ "${BUILD_BACKEND}" == 'poetry' ]]; then
           poetry install --with doc
         else
           python -m pip install .[doc]
@@ -310,34 +326,44 @@ runs:
 
     - name: "Build HTML, PDF, and JSON documentation"
       if: inputs.requires-xvfb == 'false'
+      env:
+        SPHINXOPTS: ${{ inputs.sphinxopts }}
+        SKIP_JSON_BUILD: ${{ inputs.skip-json-build }}
+        CHECK_LINKS: ${{ inputs.check-links }}
+        SPHINX_BUILD_MAKE: ${{ steps.environment-variables.outputs.SPHINX_BUILD_MAKE }}
       shell: bash
       run: |
         source .venv/bin/activate
-        ${{ env.SPHINX_BUILD_MAKE }} -C doc html SPHINXOPTS="${{ inputs.sphinxopts }}"
-        ${{ env.SPHINX_BUILD_MAKE }} -C doc pdf
-        if [[ ${{ inputs.check-links }} == 'true' ]];
+        ${SPHINX_BUILD_MAKE} -C doc html SPHINXOPTS="${SPHINX_OPTS}"
+        ${SPHINX_BUILD_MAKE} -C doc pdf
+        if [[ "${CHECK_LINKS}" == 'true' ]];
         then
-          ${{ env.SPHINX_BUILD_MAKE }} -C doc linkcheck SPHINXOPTS="${{ inputs.sphinxopts }}"
+          $SPHINX_BUILD_MAKE -C doc linkcheck SPHINXOPTS="${SPHINX_OPTS}"
         fi
-        if [[ ${{ inputs.skip-json-build }} == 'false' ]];
+        if [[ "${SKIP_JSON_BUILD}" == 'false' ]];
         then
-          ${{ env.SPHINX_BUILD_MAKE }} -C doc json SPHINXOPTS="${{ inputs.sphinxopts }}"
+          ${SPHINX_BUILD_MAKE} -C doc json SPHINXOPTS="${SPHINX_OPTS}"
         fi
 
     - name: "Build HTML, PDF, and JSON documentation using xvfb"
       if: inputs.requires-xvfb == 'true'
+      env:
+        SPHINXOPTS: ${{ inputs.sphinxopts }}
+        SKIP_JSON_BUILD: ${{ inputs.skip-json-build }}
+        CHECK_LINKS: ${{ inputs.check-links }}
+        SPHINX_BUILD_MAKE: ${{ steps.environment-variables.outputs.SPHINX_BUILD_MAKE }}
       shell: bash
       run: |
         source .venv/bin/activate
-        xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc html SPHINXOPTS="${{ inputs.sphinxopts }}"
-        xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc pdf
-        if [[ ${{ inputs.check-links }} == 'true' ]];
+        xvfb-run ${SPHINX_BUILD_MAKE} -C doc html SPHINXOPTS="${SPHINX_OPTS}"
+        xvfb-run ${SPHINX_BUILD_MAKE} -C doc pdf
+        if [[ "${CHECK_LINKS}" == 'true' ]];
         then
-          xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc linkcheck SPHINXOPTS="${{ inputs.sphinxopts }}"
+          xvfb-run $SPHINX_BUILD_MAKE -C doc linkcheck SPHINXOPTS="$SPHINX_OPTS"
         fi
-        if [[ ${{ inputs.skip-json-build }} == 'false' ]];
+        if [[ "$SKIP_JSON_BUILD" == 'false' ]];
         then
-          xvfb-run ${{ env.SPHINX_BUILD_MAKE }} -C doc json SPHINXOPTS="${{ inputs.sphinxopts }}"
+          xvfb-run ${SPHINX_BUILD_MAKE} -C doc json SPHINXOPTS="${SPHINX_OPTS}"
         fi
 
     # ------------------------------------------------------------------------
@@ -380,48 +406,60 @@ runs:
           Check if expected directories exist.
 
     - name: Set expected build directory
+      id: set-expected-build-directory
       if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
       shell: bash
       run: |
-        echo "EXPECTED_BUILD_DIR=doc/_build" >> $GITHUB_ENV
+        echo "EXPECTED_BUILD_DIR=doc/_build" >> ${GITHUB_OUTPUT}
 
     - name: Check expected build directory
+      id: check-expected-build-dir
       if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
+      env:
+        EXPECTED_BUILD_DIR: ${{ steps.set-expected-build-directory.outputs.EXPECTED_BUILD_DIR }}
       shell: bash
       run: |
-        echo "EXISTS_EXPECTED_BUILD_DIR=$( [ -d ${{ env.EXPECTED_BUILD_DIR }} ] && echo 'true' || echo 'false' )" >> $GITHUB_ENV
+        echo "EXISTS_EXPECTED_BUILD_DIR=$( [ -d "${EXPECTED_BUILD_DIR}" ] && echo 'true' || echo 'false' )" >> ${GITHUB_OUTPUT}
 
     - uses: ansys/actions/_logging@main
-      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_BUILD_DIR == 'false') }}
+      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (steps.check-expected-build-dir.outputs.EXISTS_EXPECTED_BUILD_DIR == 'false') }}
       with:
         level: "ERROR"
         message: >
-          Expected build directory ${{ env.EXPECTED_BUILD_DIR }} does not exist.
+          Expected build directory ${{ steps.set-expected-build-directory.outputs.EXPECTED_BUILD_DIR }} does not exist.
 
     - name: Set expected download directory
+      id: set-expected-download-directory
       if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
+      env:
+        EXPECTED_BUILD_DIR: ${{ steps.set-expected-build-directory.outputs.EXPECTED_BUILD_DIR }}
       shell: bash
       run: |
-        echo "EXPECTED_DOWNLOAD_DIR=$(echo '${{ env.EXPECTED_BUILD_DIR }}/html/_static/assets/download')" >> $GITHUB_ENV
+        echo "EXPECTED_DOWNLOAD_DIR=$(echo "${EXPECTED_BUILD_DIR}/html/_static/assets/download")" >> ${GITHUB_OUTPUT}
 
     - name: Check expected download directory
+      id: check-expected-download-directory
       if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
+      env:
+        EXPECTED_DOWNLOAD_DIR: ${{ steps.set-expected-download-directory.outputs.EXPECTED_DOWNLOAD_DIR }}
       shell: bash
       run: |
-        echo "EXISTS_EXPECTED_DOWNLOAD_DIR=$( [ -d '${{ env.EXPECTED_DOWNLOAD_DIR }}' ] && echo 'true' || echo 'false' )" >> $GITHUB_ENV
+        echo "EXISTS_EXPECTED_DOWNLOAD_DIR=$( [ -d "${EXPECTED_DOWNLOAD_DIR}" ] && echo 'true' || echo 'false' )" >> ${GITHUB_OUTPUT}
 
     - uses: ansys/actions/_logging@main
-      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
+      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (steps.check-expected-download-directory.outputs.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
       with:
         level: "WARNING"
         message: >
-          Expected build directory ${{ env.EXPECTED_DOWNLOAD_DIR }} does not exist. Creating it...
+          Expected build directory ${{ steps.set-expected-download-directory.outputs.EXPECTED_DOWNLOAD_DIR }} does not exist. Creating it...
 
     - name: Create expected download directory
-      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (env.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
+      if: ${{ (inputs.add-pdf-html-docs-as-assets == 'true') && (steps.check-expected-download-directory.outputs.EXISTS_EXPECTED_DOWNLOAD_DIR == 'false') }}
       shell: bash
+      env:
+        EXPECTED_DOWNLOAD_DIR: ${{ steps.set-expected-download-directory.outputs.EXPECTED_DOWNLOAD_DIR }}
       run: |
-        mkdir -p ${{ env.EXPECTED_DOWNLOAD_DIR }}
+        mkdir -p "${EXPECTED_DOWNLOAD_DIR}"
 
     # ------------------------------------------------------------------------
 
@@ -437,20 +475,24 @@ runs:
       if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
       uses: vimtor/action-zip@1379ea20d4c5705669ba81fd626dd01b1c738f26 # v1.2
       with:
-        files: ${{ env.EXPECTED_BUILD_DIR }}/html
+        files: ${{ steps.set-expected-build-directory.outputs.EXPECTED_BUILD_DIR }}/html
         dest: documentation-html.zip
 
     - name: Add assets to HTML docs
       if: ${{ inputs.add-pdf-html-docs-as-assets == 'true' }}
       shell: bash
+      env:
+        EXPECTED_BUILD_DIR: ${{ steps.set-expected-build-directory.outputs.EXPECTED_BUILD_DIR }}
+        EXPECTED_DOWNLOAD_DIR: ${{ steps.set-expected-download-directory.outputs.EXPECTED_DOWNLOAD_DIR }}
+        PDF_FILENAME: ${{ env.PDF_FILENAME }}
       run: |
-        mv documentation-html.zip ${{ env.EXPECTED_DOWNLOAD_DIR }}
-        if [ -e  "${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }}" ]; then
-            cp ${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }} ${{ env.EXPECTED_DOWNLOAD_DIR }}
-            echo "File ${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }} has been copied."
+        mv documentation-html.zip ${EXPECTED_DOWNLOAD_DIR}
+        if [ -e  "${EXPECTED_BUILD_DIR}/latex/${PDF_FILENAME}" ]; then
+            cp ${EXPECTED_BUILD_DIR}/latex/${PDF_FILENAME} ${EXPECTED_DOWNLOAD_DIR}
+            echo "File ${EXPECTED_BUILD_DIR}/latex/${PDF_FILENAME} has been copied."
         else
-            cp ${{ env.EXPECTED_BUILD_DIR }}/latex/*.pdf ${{ env.EXPECTED_DOWNLOAD_DIR }}
-            echo "Couldn't find ${{ env.EXPECTED_BUILD_DIR }}/latex/${{ env.PDF_FILENAME }}, every existing PDF file has been copied."
+            cp ${EXPECTED_BUILD_DIR}/latex/*.pdf ${EXPECTED_DOWNLOAD_DIR}
+            echo "Couldn't find ${EXPECTED_BUILD_DIR}/latex/${PDF_FILENAME}, every existing PDF file has been copied."
         fi
 
     # ------------------------------------------------------------------------
