feat: copy the index.html content from version/stable

diff --git a/doc-deploy-stable/action.yml b/doc-deploy-stable/action.yml
--- a/doc-deploy-stable/action.yml
+++ b/doc-deploy-stable/action.yml
@@ -387,20 +387,39 @@ runs:
       run: |
         echo "REDIRECTION_URL=https://${{ inputs.cname }}/version/stable/" >> $GITHUB_ENV
 
-    - name: "Create the 'index.html' redirection file"
+    - name: "Use the latest 'index.html' in base index.html page"
       shell: bash
       run: |
-        echo "<!DOCTYPE html>" > index.html
-        echo "<meta charset=\"utf-8\">" >> index.html
-        if [ -z "${{ inputs.redirection-title }}" ]; then
-          echo "<title>Redirecting to ${{ env.REDIRECTION_URL }}</title>" >> index.html
+        if [[ -f 'version/stable/index.html' ]]; then
+          cp version/stable/index.html index.html
         else
-          echo "<title>${{ inputs.redirection-title }}</title>" >> index.html
+          cp version/dev/index.html index.html
         fi
-        echo "<meta name=\"description\" content=\"${{ inputs.redirection-description }}\">" >> index.html
-        echo "<meta http-equiv=\"refresh\" content=\"0; URL=${{ env.REDIRECTION_URL }}\">" >> index.html
-        echo "<link rel=\"canonical\" href=\"${{ env.REDIRECTION_URL }}\">" >> index.html
 
+    - name: "Update all the href and source links to version/stable"
+      shell: bash
+      run: |
+        if [[ ! -f 'index.html' ]]; then
+          echo -e "\033[1;91m[ERROR]: The 'index.html' file does not exist.\033[0m"
+          exit 1
+        fi
+
+        # Define the regex pattern to match src and href attributes
+        pattern='(src|href)="([^"]*)"'
+
+        # Loop through each matched occurrence and update the file
+        while IFS= read -r line; do
+          if [[ $line =~ $pattern ]]; then
+            url="${BASH_REMATCH[2]}"
+            if [[ $url != http://* && $url != https://* ]]; then
+                new_url="version/stable/$url"
+                # Replace the original URL with the modified one
+                sed -i "s@$url@$new_url@" index.html
+                echo "Updated $url to $new_url"
+            fi
+          fi
+        done < <(grep -oE "$pattern" index.html)
+          
     - name: "Show the contents of the 'index.html' redirection file"
       shell: bash
       run: |
