FIX: conditional syntax

diff --git a/branch-name-style/action.yml b/branch-name-style/action.yml
--- a/branch-name-style/action.yml
+++ b/branch-name-style/action.yml
@@ -9,26 +9,21 @@ runs:
   using: "composite"
   steps:
 
-    - name: "Get the prefix of the branch"
-      shell: bash
-      if: github.ref_type == 'branch'
-      run: |
-        branch_name=${{ github.head_ref || github.ref }}
-        branch_prefix=$(echo "$branch_name" | cut -d '/' -f 1)
-        echo "BRANCH_PREFIX=$branch_prefix" >> $GITHUB_ENV
-
     - name: "Check if branch has a valid prefix"
       shell: bash
       if: github.ref_type == 'branch'
       run: |
-        branch_name=${{ env.BRANCH_NAME }}
+        branch_name=${{ github.head_ref || github.ref }}
+
         if [[ $branch_name != */* ]]; then
-          echo "\033[1;91m[ERROR]: Branch name ${{ env.BRANCH_NAME }} does not contain a prefix and a backslash." >&2
+          echo "\033[1;91m[ERROR]: Branch name $branch_name does not contain a prefix and a backslash." >&2
           exit 1
         fi
 
+        branch_prefix=$(echo "$branch_name" | cut -d '/' -f 1)
         valid_prefixes=("fix" "feat" "junk" "maint" "doc" "no-ci" "test" "release")
-        if [[ ! ${valid_prefixes[@]} =~ ${{ env.BRANCH_PREFIX }} ]]; then
-          echo "\033[1;91m[ERROR]: Branch name ${{ env.BRANCH_PREFIX }} prefix is not valid." >&2
+
+        if [[ ! ${valid_prefixes[@]} =~ $branch_prefix ]]; then
+          echo "\033[1;91m[ERROR]: Branch name $branch_prefix prefix is not valid." >&2
           exit 1
         fi
