feat: ensure matching and metadata version

diff --git a/build-library/action.yml b/build-library/action.yml
--- a/build-library/action.yml
+++ b/build-library/action.yml
@@ -108,6 +108,22 @@ runs:
     - name: "Install Git and clone project"
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
+    - name: "Ensure tag version matches metadata version when triggered by push of tags"
+      if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
+      shell: bash
+      env:
+        TAG_REF: ${{ github.ref_name }}
+      run: |
+        PYPROJECT_TOML_VERSION=$(grep '^version' pyproject.toml | sed -E 's/version = "(.*)"/\1/')
+        if [[ $PYPROJECT_TOML_VERSION == $TAG_REF ]]; then
+          echo "Tag version matches metadata version. Proceeding with the build."
+        else
+          echo "Tag version does not match metadata version. Exiting with error."
+          echo "Tag version: $TAG_REF"
+          echo "Metadata version: $PYPROJECT_TOML_VERSION"
+          exit 1
+        fi
+
     - name: "Set up Python"
       uses: ansys/actions/_setup-python@main
       with:
