fix: review suggestions

diff --git a/build-library/action.yml b/build-library/action.yml
--- a/build-library/action.yml
+++ b/build-library/action.yml
@@ -122,30 +122,21 @@ runs:
       run: |
         $INSTALL_COMMAND .
 
-    - name: "Verify library is properly installed and get its version number"
-      id: library-version
-      shell: bash
-      env:
-        LIBRARY_NAME: ${{ inputs.library-name }}
-      run: |
-        library_name="${LIBRARY_NAME}"
-
-        version=$(python -c "import importlib.metadata as importlib_metadata; print(importlib_metadata.version('$library_name'))")
-        if [ -z "$version" ]; then
-            echo "Problem getting the library version"
-            exit 1;
-        else
-            echo "The library version is: $version";
-        fi;
-        echo "library_version=${version}" >> ${GITHUB_OUTPUT}
-
     - name: "Ensure tag version matches metadata version when triggered by push of tags"
       if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
       shell: bash
       env:
         TAG_REF: ${{ github.ref_name }}
-        LIBRARY_VERSION: ${{ steps.library-version.outputs.library_version }}
+        LIBRARY_NAME: ${{ inputs.library-name }}
       run: |
+        LIBRARY_VERSION=$(python -c "import importlib.metadata as importlib_metadata; print(importlib_metadata.version('$LIBRARY_NAME'))")
+        if [ -z "$LIBRARY_VERSION" ]; then
+            echo "Problem getting the library version. Exiting with error."
+            exit 1
+        else
+            echo "The library version is: $LIBRARY_VERSION";
+        fi
+
         if [[ v${LIBRARY_VERSION} == $TAG_REF ]]; then
           echo "Tag version matches metadata version. Proceeding with the build."
         else
