ci: split workflows (#701)

diff --git a/.github/workflows/ci_cd_release.yml b/.github/workflows/ci_cd_release.yml
--- a/.github/workflows/ci_cd_release.yml
+++ b/.github/workflows/ci_cd_release.yml
@@ -1,19 +1,15 @@
-name: CI
+name: release
 on:
-  pull_request:
-  workflow_dispatch:
   push:
+    branches:
+      - 'release/*'
     tags:
       - "v*.*.*"
-    branches:
-      - main
 
 env:
-  MAIN_PYTHON_VERSION: '3.11'
+  MAIN_PYTHON_VERSION: '3.12'
   DOCUMENTATION_CNAME: 'actions.docs.ansys.com'
-  test-library-name: 'ansys-actions'
-  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
-  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}
+  LIBRARY_NAME: 'ansys-actions'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -21,62 +17,81 @@ concurrency:
 
 jobs:
 
-  labeler:
-    name: "Labels"
-    permissions:
-      contents: read
-      pull-requests: write
+  rolling-release:
+    name: "Rolling release"
     runs-on: ubuntu-latest
+    permissions: write-all
     steps:
-     - uses: actions/checkout@v4
 
-     - name: "Update labels"
-       uses: micnncim/action-label-syncer@v1
-       env:
-         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    - name: "Checkout repository"
+      uses: actions/checkout@v4
+      with:
+        fetch-tags: true
+        ref: ${{ github.ref }}
 
-     - name: "Label pull-request"
-       # Skip if user does not have write permissions - PR coming from a fork
-       if: github.event.pull_request.head.repo.full_name == github.repository
-       uses: actions/labeler@v5.0.0
-       with:
-        repo-token: ${{ secrets.GITHUB_TOKEN }}
+    - name: "Configure git"
+      run: |
+        git config user.name github-actions
+        git config user.email github-actions@github.com
 
-  pr-title-style:
-    name: "Pull-request title style"
-    runs-on: ubuntu-latest
-    needs: labeler
-    steps:
-      - uses: ansys/actions/check-pr-title@main
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+    - name: "Decompose tag into components"
+      run: |
+        if [[ ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          VERSION=$(echo ${{ github.ref_name}} | cut -d 'v' -f2)
+          MAJOR=$(echo "${VERSION}" | cut -d '.' -f1)
+          MINOR=$(echo "${VERSION}" | cut -d '.' -f2)
+          PATCH=$(echo "${VERSION}" | cut -d '.' -f3)
+        else
+          echo "::error::Invalid tag format. Expected vX.Y.Z but got ${{ github.ref_name }}"
+          exit 1
+        fi
+
+    - name: "Check tag is valid for current branch"
+      run: |
+        if [[ ${{ github.event.base_ref }} != "refs/heads/release/${env.MAJOR}.${{ env.MINOR }}" ]]; then
+          echo "::error::Tag ${{ github.ref_name }} does not match branch version. wrong branch."
+          exit 1
+        fi
+
+    - name: "Remove MAJOR tag"
+      run: |
+        if git tag -l | grep -q "^${{ env.MAJOR }}$"; then
+          git push --delete origin ${{ env.MAJOR }}
+        else
+          echo -e "Tag ${{ env.MAJOR }} does not exist, skipping deletion."
+        fi
+
+    - name: "Remove MAJOR.MINOR tag"
+      run: |
+        if git tag -l | grep -q "^${{ env.MAJOR }}\.${{ env.MINOR }}$"; then
+          git push --delete origin ${{ env.MAJOR }}.${{ env.MINOR }}
+        else
+          echo -e "Tag ${{ env.MAJOR }}.${{ env.MINOR }} does not exist, skipping deletion."
+        fi
+
+    - name: "Create new tags"
+      run: |
+          git tag ${{ env.MAJOR }}.${{ env.MINOR }}
+          git tag ${{ env.MAJOR }}
+          git push origin ${{ env.MAJOR }}.${{ env.MINOR }}
+          git push origin ${{ env.MAJOR }}
 
   code-style:
     name: "Code style"
     runs-on: ubuntu-latest
-    needs: pr-title-style
+    needs: rolling-release
     steps:
-      - name: "Run code style checks"
-        uses: ansys/actions/code-style@main
+      - uses: ansys/actions/code-style@main
         with:
           python-version: ${{ env.MAIN_PYTHON_VERSION }}
           use-python-cache: false
 
-      - name: "Verify private actions are not pointing to the 'main' branch"
-        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
-        run: |
-          if $(grep -q --exclude-dir={.git,.github,doc} "ansys\/actions\/.*\@main" -r .); then
-            echo -e "\033[1;91m[ERROR]: Found private actions pointing to the 'main' branch.\033[0m"
-            grep -q --exclude-dir={.git,.github,doc} "ansys\/actions\/.*\@main" -r .
-          fi
-
   doc-style:
     name: "Doc style"
     runs-on: ubuntu-latest
-    needs: pr-title-style
+    needs: rolling-release
     steps:
-      - name: "Run documentation style checks"
-        uses: ansys/actions/doc-style@main
+      - uses: ansys/actions/doc-style@main
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
 
@@ -85,8 +100,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: doc-style
     steps:
-      - name: "Build documentation"
-        uses: ansys/actions/doc-build@main
+      - uses: ansys/actions/doc-build@main
         with:
           skip-install: true
           python-version: ${{ env.MAIN_PYTHON_VERSION }}
@@ -112,7 +126,7 @@ jobs:
         use-cache: false
 
     - name: "Isolate testing library"
-      run: mv .ci/${{ env.test-library-name }} ~/
+      run: mv .ci/${{ env.LIBRARY_NAME }} ~/
 
     - name: "Install build and twine"
       shell: bash
@@ -122,34 +136,21 @@ jobs:
     - name: "Build distribution artifacts and check their health"
       shell: bash
       run: |
-        cd ~/${{ env.test-library-name }}
+        cd ~/${{ env.LIBRARY_NAME }}
         ls -R && python -m build && python -m twine check dist/*
 
     - name: "Upload distribution artifacts to GitHub artifacts"
       uses: actions/upload-artifact@v4
       with:
-        name: ${{ env.test-library-name }}-artifacts
-        path: ~/${{ env.test-library-name }}/dist/
+        name: ${{ env.LIBRARY_NAME }}-artifacts
+        path: ~/${{ env.LIBRARY_NAME }}/dist/
         retention-days: 7
 
     - name: "Release to the test PyPI repository"
       uses: ansys/actions/release-pypi-test@main
       with:
-        library-name: ${{ env.test-library-name }}
+        library-name: ${{ env.LIBRARY_NAME }}
         use-trusted-publisher: true
-
-  doc-deploy-dev:
-    name: "Deploy developers documentation"
-    runs-on: ubuntu-latest
-    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags')
-    needs: [doc-build, tests]
-    steps:
-      - uses: ansys/actions/doc-deploy-dev@main
-        with:
-            cname: ${{ env.DOCUMENTATION_CNAME }}
-            token: ${{ secrets.GITHUB_TOKEN }}
-            bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
-            bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
 
   release:
     name: "Release to GitHub"
@@ -202,7 +203,7 @@ jobs:
     steps:
       - uses: ansys/actions/doc-deploy-stable@main
         with:
-            cname: ${{ env.DOCUMENTATION_CNAME }}
-            token: ${{ secrets.GITHUB_TOKEN }}
-            bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
-            bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
+          cname: ${{ env.DOCUMENTATION_CNAME }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
+          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
